import { StyleSheet } from 'react-native';
import { useTheme } from '../context/ThemeContext';

const getStyles = (theme) => StyleSheet.create({
  screenContainer: { flex: 1, backgroundColor: theme.colors.background },
  header: {
    backgroundColor: theme.colors.primary, 
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.m,
    paddingVertical: theme.spacing.s,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    borderTopColor: 'transparent', 
  },
  titleInput: {
    flex: 1,
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.colors.text2,
    fontFamily: 'TitilliumWeb_700Bold',
  },
  bottomBar: {
    backgroundColor: theme.colors.primary, 
    height:30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.m,
    paddingVertical: theme.spacing.s,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopColor: 'transparent', 
  },
  formContainer: { paddingHorizontal: theme.spacing.m },
  row: {
    flexDirection: 'row', 
    alignItems: 'center', 
    paddingVertical: theme.spacing.m,
    borderBottomWidth: 1, 
    borderBottomColor: theme.colors.border,
  },
  icon: { marginRight: theme.spacing.m },
  label: {
    flex: 1, 
    fontSize: 18, 
    color: theme.colors.text,
    fontFamily: 'TitilliumWeb_400Regular',
  },
  valueText: {
    fontSize: 16, 
    color: theme.colors.inactive,
    fontFamily: 'TitilliumWeb_400Regular',
  },
  iconCircle: {
    width: 44, 
    height: 44, 
    borderRadius: 22, 
    justifyContent: 'center',
    alignItems: 'center', 
    marginRight: theme.spacing.m,
    backgroundColor: theme.colors.border,
  },
  colorCircle: {
    width: 24, 
    height: 24, 
    borderRadius: 12, 
    marginRight: theme.spacing.m,
    borderWidth: 1, 
    borderColor: theme.colors.border,
  },
  dropdownList: {
    width: 150,
    height: 'auto',
    maxHeight: 200,
    borderColor: theme.colors.border,
    borderWidth: 1, 
    borderRadius: 8,
    backgroundColor: theme.colors.card,
    marginTop: -20,
  },
  dropdownText: { 
    fontSize: 16, 
    color: theme.colors.text, 
    padding: 10,
    backgroundColor: theme.colors.card,
    textAlign: 'center',
  },
  dropdownTextHighlight: {
    backgroundColor: theme.colors.primary,
    color: '#FFF',
  },
  createButton: {
    backgroundColor: theme.colors.primary, 
    borderRadius: 25, 
    padding: theme.spacing.m,
    alignItems: 'center', 
    margin: theme.spacing.m, 
    marginTop: theme.spacing.l,
  },
  createButtonText: {
    color: 'white', 
    fontSize: 18, 
    fontFamily: 'TitilliumWeb_700Bold',
  },
  numberInput: {
    fontSize: 18,
    color: theme.colors.text,
    fontFamily: 'TitilliumWeb_700Bold',
    paddingHorizontal: theme.spacing.m,
    paddingVertical: theme.spacing.s / 2,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    width: 60,
    textAlign: 'center',
  },
  labelSuffix: {
    fontSize: 16,
    color: theme.colors.inactive,
    fontFamily: 'TitilliumWeb_400Regular',
    marginLeft: theme.spacing.s,
  },
  indentedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: theme.spacing.m,
    paddingHorizontal: theme.spacing.m,
    backgroundColor: theme.colors.card,
    borderRadius: 8,
    marginVertical: theme.spacing.s,
  },
  dayCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.border,
  },
  dayCircleSelected: {
    backgroundColor: theme.colors.primary,
  },
  dayText: {
    fontSize: 16,
    color: theme.colors.inactive,
    fontFamily: 'TitilliumWeb_700Bold',
  },
  dayTextSelected: {
    color: 'white',
  },
  timePickerContainer: {
    paddingVertical: theme.spacing.m,
    paddingHorizontal: theme.spacing.m,
    backgroundColor: theme.colors.card,
    borderRadius: 8,
  },
  timeButton: {
    padding: theme.spacing.s,
    backgroundColor: theme.colors.border,
    borderRadius: 8,
    margin: theme.spacing.s,
  },
  timeText: {
    fontSize: 16,
    color: theme.colors.text,
    fontFamily: 'TitilliumWeb_700Bold',
  },
  dayTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.s,
  },
  dayTimeLabel: {
    fontSize: 16,
    color: theme.colors.text,
    fontFamily: 'TitilliumWeb_700Bold',
  },
  timeButtonsGroup: {
    flexDirection: 'row',
  },
});
