export const availableIcons = [
  { name: 'star', label: 'Gwiazda, ogólne' },
  { name: 'heart', label: 'Serce, zdrowie' },
  { name: 'book', label: 'Książka, nauka' },
  { name: 'briefcase', label: 'Teczka, praca' },
  { name: 'running', label: 'Bieganie, sport' },
  { name: 'dumbbell', label: 'Ciężarek, siłownia' },
  { name: 'walking', label: 'Chodzenie, spacer' },
  { name: 'bed', label: 'Łóżko, sen' },
  { name: 'tint', label: 'Kropla, picie wody' },
  { name: 'utensils', label: 'Sztućce, jedzenie' },
  { name: 'pills', label: 'Tabletki, leki' },
  { name: 'home', label: 'Dom' },
  { name: 'shopping-cart', label: 'Wózek, zakupy' },
  { name: 'money-bill-wave', label: 'Banknot, finanse' },
  { name: 'gamepad', label: 'Pad, rozrywka' },
  { name: 'music', label: 'Nuta, muzyka' },
  { name: 'paint-brush', label: 'Pędzel, kreatywność' },
  { name: 'dog', label: 'Pies, zwierzęta' },
  { name: 'broom', label: 'Miotła, sprzątanie' },
  { name: 'check', label: 'Zrobione' },
];